language: node_js

node_js:
    - stable
    - 12
    - 11
    - 10
    - 9
    - 8

script:
    - npm install -g codecov
    - npm i
    - npm run build
    - npm run test:coverage
    - npm run test:lint
    - npm run report:coverage
