language: node_js
os: linux
dist: jammy

node_js:
    - 19
    - 18
    - 17
    - 16

script:
    - npm install -g codecov
    - npm i
    - npm run build
    - npm run test:coverage
    - npm run test:lint
    - npm run report:coverage
